using CmdLineArgsParser;
using CmdLineArgsParser.Attributes;

namespace dyndnsupdate;

public class Options : IOptions
{
    [Option("hostname", 'h',
        Description = "The hostname generated by dyndns.it",
        Required = true)]
    public string? Hostname { get; set; }

    [Option("username", 'u',
        Description = "Your dyndns.it username",
        Required = true)]
    public string? Username { get; set; }

    [Option("password", 'p',
        Description = "Your dyndns.it password",
        Required = true)]
    public string? Password { get; set; }
}